### PR TITLE
Bootstrap Docs

### PR DESCRIPTION
**Pull request by leostera**
Hello Andreas! I figured I'd just submit a PR that gets things started so you can document more easily. It will:

- [x] Add a command to quickly generate them. Running `yarn docs` will build the docs or guide you through the setup to build them (installing the right `opam` switch, and installing `odoc` from it too).

- [x] Be easy to publish. If you keep the generated `docs` folder in branch you can just enable the Github Pages to be served from there and `eldh.github.io/bs-react/` should show the docs 👌 

- [x] Includes a small starting manual for you to continue writing 📝 

Left some tiny notes on the commits, let me know if I should clarify anything else!

Screenshots:
screen shot 2018-12-04 at 15 27 54

screen shot 2018-12-04 at 15 27 59

screen shot 2018-12-04 at 15 28 05

### CODE REVIEW

**Comment by eldh** [comment]
Awesome!!! How far away is npm support for odoc? From the repo it looked like it's on the way? I saw something about bsdoc, is that ready to be used?

**Comment by eldh** [comment]
I didn't really understand how to get it to pick up comments in the `.rei` files, you mind adding just a dummy example of that?

**Comment by leostera** [comment]
@eldh I modified a .rei file so it picks up the docs :)

You'll see that the markdown is not valid, and that some other small things change. This is because `odoc` and `bsdoc` work with `ocamldoc` formatting.

If you want to see a more extensive example of this, the [ReActor docs](https://github.com/ostera/reactor/blob/master/src/ReActor.rei) use plenty of features ([preview](https://ostera.github.io/reactor/docs/ReActor/)).

**Comment by leostera** [comment]
Regarding `bsdoc` we can try to use it but I'm still working out some rough edges. Let me know if you'd like to volunteer `bs-react` as an early user of it and I'll replace the scripts with the proper dependency :) 

Otherwise we can do it in a next PR!

**Comment by eldh** [comment]
Let's do it in the next step :) But I'd love to try it out! Just let me know when you think it's good enough :D

**Comment by eldh** [comment]
Thanks a lot for this!!! Great first step, I'll try to add some nice comments soon!

**Pull request merged**
